### ISSUE TITLE
investigate alternative hosting to github pages

### ISSUE THREAD

**Issue by jedahan** [kiss-community/kisscommunity.org#3]

**Comment by dilyn-corner** [comment]
Coming back to a lot of old issues; if you want we can directly host the site on the Linode instance that hosts all of the subdomains.
I plan on looking into accounts/mails/quotas/user admin/etc this weekend before the new year comes into full swing and kicks my ass, so we could potentially set something up where you can access the node before the end of the month to manage the site.
