### ISSUE TITLE
Further distinguish Community from upstream

### ISSUE THREAD

**Issue by dilyn-corner** [kiss-community/kisscommunity.org#8]
Per https://github.com/kisslinux/website/issues/88 we should look into making the fact that we aren't officially associated with KISS more transparent. 

I think a solid and easy way of doing this on the website is adding some extra blurb at the top with the other two that exist ("When dylan..."\n "KISS Linux..."\n) saying something like "KISS-Community is a coalition of KISS users and is not affiliated with or officially supported by Dylan Araps or KISS Linux" (add and subtract words as necessary; this is just an example to show the spirit of what should be said).

**Comment by AndreiSva** [comment]
Also, I think we should consider creating our own branding / modification based on the KISS Linux logo to add to the github organization and the community website. Maybe we could do a logo contest?

**Comment by dilyn-corner** [comment]
True, though I did not want to bring that up on this repo because it's "out of scope" (this is just the website, which as far as I know isn't using any special branding at all). 

For anyone reading this, getting a new logo within the next week would be wonderful. I was a fan of @jedahan's lipstick emoji idea, but I'm a sucker for themes.

**Comment by dilyn-corner** [comment]
We've changed the logo for the GitHub org -- is there more than should be done?
